### ISSUE TITLE
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.

### ISSUE THREAD

**Issue by SeekPoint** [luochana/toutiaoSpider#1]
C:\ub16_prj\toutiaoSpider>scrapy crawl tt

DevTools listening on ws://127.0.0.1:63209/devtools/browser/03fef8be-c571-44e0-9472-ee8d6f727506
2019-03-27 01:50:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.toutiao.com via http://localhost:8050/render.html>
Traceback (most recent call last):
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-03-27 01:54:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.toutiao.com via http://localhost:8050/render.html>
Traceback (most recent call last):
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-03-27 01:54:06 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.toutiao.com via http://localhost:8050/render.html>
Traceback (most recent call last):
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 10061: 由于目标计算机积极拒绝，无法连接。.
2019-03-27 01:54:10 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.toutiao.com via http://localhost:8050/render.html>

**Comment by luochana** [comment]
Splash得到正确渲染了吗

**Comment by luochana** [comment]
看着就像Splash环境没配好

**Comment by banyiluoyun** [comment]
splash没有配置好
